GET http://localhost:50560/ HTTP/1.1

###
POST http://localhost:50560/register HTTP/1.1
Content-Type: application/json

{
    "secret": "P19wvm0bOm",
    "password": "testing",
    "name": "Test",
    "email": "testing@testing.com"
}

###
GET http://localhost:50560/login HTTP/1.1
Content-Type: application/json

{
    "password": "testing",
    "email": "testing@testing.com"
}

###
POST http://localhost:50908/project/ HTTP/1.1
