GET http://localhost:8000/ HTTP/1.1

###
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "secret": "P19wvm0bOm",
    "password": "testing1",
    "name": "Test1",
    "email": "testing1@testing.com"
}

###
GET http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "password": "testing1",
    "email": "testing1@testing.com"
}

###
POST http://localhost:8000/project/ HTTP/1.1
Content-Type: application/json

{
	"title": "something",
	"description": "something_test",
	"supervisor": "teacher",
    "images": ["something", "something_else"]
}

###
GET http://localhost:8000/project HTTP/1.1

###
DELETE http://localhost:8000/project/2 HTTP/1.1