GET http://localhost:8000/ HTTP/1.1

###
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "secret": "P19wvm0bOm",
    "password": "Pijulkinas1",
    "name": "Pijus Serapinas",
    "email": "serapinaspijus@gmail.com"
}

###
POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "password": "Pijulkinas1",
    "email": "serapinaspijus@gmail.com"
}

###
POST http://localhost:8000/project/ HTTP/1.1
Content-Type: application/json

{
	"title": "Pirmasis darbas",
	"description": "testuojam, žiūrim ar viskas veikia",
	"supervisor": "Lina",
    "images": ["http://tny.im/rtS", "http://tny.im/rtT"]
}

###
GET http://localhost:8000/project HTTP/1.1

###
DELETE http://localhost:8000/project/2 HTTP/1.1

###
PATCH  http://localhost:8000/project/9 HTTP/1.1
Content-Type: application/json

{
    "title": "Pakeičiau Title iš \"Pirmasis darbas\""
}

###
GET http://localhost:8000/user HTTP/1.1

###
DELETE  http://localhost:8000/login HTTP/1.1

###
GET http://localhost:8000/reg HTTP/1.1
Content-Type: application/json

{
    "register_key": "P19wvm0bOm"
}